### ISSUE TITLE
Assumption that `id` can't be zero?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-data-resources#158]
Say I have:

```js
@tracked id = 0;

data = findRecord(this, 'post', () => this.id);
```

This will throw:

```
Uncaught (in promise) Error: Assertion Failed: Expected an ID to be specified from the thunk passed to findRecord
```

I can understand that `null` and `undefined` would throw, but I'm not convinced records with `id == 0` are something that should _not_ happen?

Thinking about systems that "mark" a deleted relationship (id) as something by setting `relationship_id` to zero.

**Comment by NullVoxPopuli** [comment]
yeah, def sounds like a bug. Likely a `!id` check somwhere that should be `null` and `undefined` checks instead

**Comment by NullVoxPopuli** [comment]
fixed in https://github.com/NullVoxPopuli/ember-data-resources/commit/fc6e3f67cc2978324056699f42d66cf67bd10fcf
