### ISSUE TITLE
Should `findRecord` gracefully handle undefined ID scenarios?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-data-resources#159]
Say I have:

```js
@tracked id = undefined;

blog = findRecord(this, 'blog', () => this.id)
```

And this is wanted as `id` will be filled in _later_. Either by user input or via XHR request. Right now such code would throw:

```
Uncaught (in promise) Error: Assertion Failed: Expected an ID to be specified from the thunk passed to findRecord
```

I can simply put an extra if statement everywhere _before_ touching `this.glog`, e.g:

```
{{#if this.id}}
  {{this.blog.name}}
{{/if}}
```

But this is error prone and adds if condition that is dependent on something that the call site does not really care about. Would it make sense to _not_ throw when `thunk` returns `undefined` and instead re-surface that the call has not been made via `this.blog.isInvalidId` or whatever?

**Comment by NullVoxPopuli** [comment]
hmmm maayyybe. I'm going to add a test for this behavior, and see what the error is without the assertion -- because I think (currently) ember-data then throws an error. But, I agree with you in that using the error property on the resource is probably the better thing to do here

**Comment by NullVoxPopuli** [comment]
ok, yeah, PR incoming -- should be a non-breaking change, I think -- types are also widening, so we should be good on that front, too

**Comment by NullVoxPopuli** [comment]
fixed in https://github.com/NullVoxPopuli/ember-data-resources/commit/fc6e3f67cc2978324056699f42d66cf67bd10fcf
