### ISSUE TITLE
Ember-data v4+ returns non-plain arrays, causing things like filter, attributes, etc, to not be callable/gettable

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/ember-data-resources#216]

**Comment by kitsuneyo** [comment]
I've maybe run into this issue with this line in a template:

`{{#let this.articleQuery.records.firstObject as |article|}}`

Can't replace `firstObject` with `[0]` or get the first item in the component class.

**Comment by NullVoxPopuli** [comment]
What about `.0`? Or
`{{get theArray 0}}`

**Comment by kitsuneyo** [comment]
Ah, I wasn't aware of those.

`.0` didn't seem to work but `{{#let (get this.articleQuery.records 0) as |article|}}` does, thanks :D
