### ISSUE TITLE
Bugs in findRecord

### ISSUE THREAD

**Issue by lolmaus** [NullVoxPopuli/ember-data-resources#227]
Hi!

I've tried using `findRecord` from `ember-data-resources` and failed due to two bugs:

# 1. Ignores string ids

In Ember Data, ids can be strings. Yet, `findRecord` expects the id to be a number:

https://github.com/NullVoxPopuli/ember-data-resources/blob/main/addon/js-helpers.ts#L27

When a string id is passed, `ember-data-resources` throws an error saying that the id was null or undefined, which is confusing.

# 2. Does not support documented invocation

The readme suggests using `findRecord` like this:

```
blog = findRecord(this, 'blog', () => [this.id])
```

Yet, the [code](https://github.com/NullVoxPopuli/ember-data-resources/blob/main/addon/js-helpers.ts#L30) does do anything when the `reified` (return value of callback) is an array. Instead, probably by mistake, it checks whether `options` is an array, which is always `undefined` at this point. As a result, the same error is thrown saying that the id is null or undefined.

***

With @simonihmig's approval, I could work on improving code coverage and edge case handling. I believe it should not throw the "null or undefined" error for any type other than number or array. And when the result is an array, it should check whether the id inside the array is a string or a number.

**Comment by NullVoxPopuli** [comment]
Woah thanks for reporting, i'm a little embarrassed those bugs exist.
Esp considering i have a type for ID which includes string: https://github.com/NullVoxPopuli/ember-data-resources/blob/main/addon/-private/resources/types.ts#L1


>probably by mistake,

Most def!

Will happily accept bug fix prs for these 😅

**Comment by lolmaus** [comment]
@NullVoxPopuli, done: https://github.com/NullVoxPopuli/ember-data-resources/pull/228
