### ISSUE TITLE
Update to ember-resources v5

### ISSUE THREAD

**Issue by anehx** [NullVoxPopuli/ember-data-resources#260]
Hi @NullVoxPopuli 

First of all, this is an awesome addon! We're using it alot in our applications.

Are there any intentions of updgrading this addon to work with the new version v5+ of `ember-resources`? I've tried upgrading it but couldn't get it to work..

Cheers!

**Comment by NullVoxPopuli** [comment]
Oh yeah, i can give that a go today! 🎉

**Comment by NullVoxPopuli** [comment]
This can't be done without a breaking change release, it turns out -- have bump the minimum required `@glimmer/component` / `@glimmer/tracking`

**Comment by NullVoxPopuli** [comment]
done in https://github.com/NullVoxPopuli/ember-data-resources/pull/261

**Comment by anehx** [comment]
Thanks so much @NullVoxPopuli !
