### ISSUE TITLE
Problems passing tracked properties into the query resource

### ISSUE THREAD

**Issue by roomman** [NullVoxPopuli/ember-data-resources#288]
Hi, I hope all is well in your world 👍🏻. I'm hoping for guidance as I've struggled to find answers in your docs. 

I have `ember-data-resources` and `ember-cloud-firestore-adapter` acting in unison, sort of. 

As you can see below, I'm trying to pass a `@tracked` property (`presenterRef`) from my Controller into the query resource. For whatever reason, I have had to declare a private `_presenterRef` in order to utilise that in the adapter's `filter` function because, when I debug in, `this.presenterRef` doesn't exist in that scope. Typescript isn't happy about this and I assume there's a better way of doing it - your own examples appear to be using `@tracked` props from the "parent" scope?

```
// Some glimmer component...

  @tracked presenterRef = 'foo';

  itineraries = query<BookingItineraryModel>(this, 'booking-itinerary', () => [
    {
      _presenterRef: this.presenterRef,

      buildReference(db: Firestore) {
        return collectionGroup(db, 'booking_itineraries');
      },

      filter(reference: CollectionReference) {
        return query(
          reference,
          where('presenter', '==', this._presenterRef),
        );
      },
    },
```

**Comment by NullVoxPopuli** [comment]
Norry i didn't get to this sooner. Saw you closed the issue. Did you find your answer?

**Comment by roomman** [comment]
I didn't but after investigating more I think the 'problem' is related to the adapter and not this repo. Thank you for checking in. 👍🏻
