### ISSUE TITLE
What is the best way to reload the data?

### ISSUE THREAD

**Issue by tdwesten** [NullVoxPopuli/ember-data-resources#293]
I'd like to refresh the data when re-entering a route, similar to the  reload: true  option in route configurations. I utilize the  query  function to load data into a headlessTable using a custom SQLite Ember Data adapter.
```
  documents = query<DocumentModel>(this, DocumentModel.modelName, () => ({
    filter: [
      {
        column: 'status',
        operator: '!=',
        value: DocumentStatus.Processed,
      },
    ],
  }));
  ```
Maybe via a `@tracked` prop? Any tips?

**Comment by NullVoxPopuli** [comment]
Where is the query called from? If in a component that is re-mounted when you re-enter your route, it should re-fetch.

**Comment by tdwesten** [comment]
The query is called from a controller. I have a table component and provide a `headlessTable` to it as a prop.

**Comment by NullVoxPopuli** [comment]
makes sense -- controllers are singletons -- so if you move `documents` to a component, your problem will be resolved.

ember-resources (and related sub-projects) don't intend to go out of their way to support controllers' goofy behaviors :sweat_smile: 


so, that would be the _best way_ to get the data reloaded. :tada: 

If you wanted minimal refactorings, you _could_ have the function consume some tracked property, but it's considered hacky, as it serves no real purpose other than working around controllers' behaviors

**Comment by NullVoxPopuli** [comment]
Gonna close this for now -- please feel free to open a new issue for new discussion!
