### ISSUE TITLE
ember-data-resources installs ember-resources@7.0.0 but does not support its interface

### ISSUE THREAD

**Issue by elfin-sbreuers** [NullVoxPopuli/ember-data-resources#383]
I just installed `ember-data-resources@5.0.0` with

```
ember install ember-data-resources
```
This installs `ember-resources@7.0.0` due to the `"ember-resources": "^5.3.0 || >= 6.0.0",` in `peerDependencies`.

Using

```
ember s
```
does yield the following error
```
WARNING in ./node_modules/ember-data-resources/dist/request-17f93aea.js 1:1352-1360
export 'Resource' (imported as 'Resource') was not found in 'ember-resources' (possible exports: cell, registerUsable, resource, resourceFactory, use)
 @ ./node_modules/ember-data-resources/dist/-private/resources/query.js 1:0-115 1:306-313 1:350-376 1:652-677 1:784-809
 @ ./node_modules/ember-data-resources/dist/index.js 1:114-163 1:114-163
 @ ../../../../../../../tmp/broccoli-547143MpIxc2V2D85D/cache-236-webpack_bundler_ember_auto_import_webpack/app.cjs 18:104-135
```
When explicitly installing
```
ember install ember-resources@6
```
this problem goes away.

So maybe the peerDependencies need to be set to "ember-resources": "^5.3.0 || ^6.0.0".

**Comment by NullVoxPopuli** [comment]
Thanks for the issue report!

This library can be compatible with ember-resources 6 and 7 via importing Resource from https://github.com/NullVoxPopuli/ember-modify-based-class-resource/

The migration is 'find and replace', which i can do soon.

**Comment by basz** [comment]
using e-r 6.5.1 or it does not work... but great stuff!

**Comment by NullVoxPopuli** [comment]
Sorry about that, forgot to publish.

_Just released_: https://github.com/NullVoxPopuli/ember-data-resources/releases/tag/v5.1.0-ember-data-resources
